import "../stylesheets/colors.scss"
import "../stylesheets/fonts.scss"
import "../stylesheets/index.scss"
import "../stylesheets/homeadmin.scss"
import "../stylesheets/admincomps.scss"
import "../stylesheets/adminnavigation.scss"